// SPDX-License-Identifier: MIT

pragma solidity ^0.8.18;

import {Script} from "forge-std/Script.sol";
import {MockV3Aggregator} from "../test/mocks/MockV3Aggregator.sol";
import { ERC20Mock } from "../test/mocks/ERC20Mock.sol";


/**
 * @title  Decentralized StableCoin HelperConfig Script
 * @author LegendaryCode
 * @notice Manages network-specific configurations for deployments and testing.
 *  @dev Inherits from Forge-std Script to allow deployment of mock contracts on local 
 *       networks.
 */
contract HelperConfig is Script  {

     /// @notice Holds configuration addresses and keys required for a specific network.
    struct NetworkConfig {
        address wethUsdPriceFeed;   // Address of the WETH/USD Chainlink price feed
        address wbtcUsdPriceFeed;   // Address of the WBTC/USD Chainlink price feed
        address weth;               // Address of the WETH ERC20 token
        address wbtc;               // Address of the WBTC ERC20 token
        uint256 deployerKey;        // Private key used to sign deployment transactions
    }

    /// @notice  Price Feed Mock Constants(Constants values for mock price feed) 
    uint8 public constant DECIMALS = 8;
    int256 public constant ETH_USD_PRICE = 2000e8;
    int256 public constant BTC_USD_PRICE = 1000e8;

    /// @dev Default private key for the first account generated by a local Anvil chain.
    uint256 public DEFAULT_ANVIL_KEY = 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80;

    /// @notice The active network configuration automatically chosen at deployment runtime.
    NetworkConfig public activeNetworkConfig;

    /// @notice Automatically sets the active configuration based on the current Chain ID.
    constructor() {
        if (block.chainid == 11155111) {
            activeNetworkConfig = getSepoliaEthConfig();
        }
        else {
            activeNetworkConfig = getOrCreateAnvilEthConfig();
        }
    }


    /**
     * @notice Retrieves hardcoded live contract addresses for the Sepolia network.
     * @dev Reads the deployer's private key directly from the environment variables.
     * @return NetworkConfig The complete configuration struct containing Sepolia addresses.
     */
    function getSepoliaEthConfig() public view returns(NetworkConfig memory) {
        return NetworkConfig({
            wethUsdPriceFeed: 0x694AA1769357215DE4FAC081bf1f309aDC325306,
            wbtcUsdPriceFeed: 0x1b44F3514812d835EB1BDB0acB33d3fA3351Ee43,
            weth: 0xdd13E55209Fd76AfE204dBda4007C227904f0a81,
            wbtc: 0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063,
            deployerKey: vm.envUint("PRIVATE_KEY")
        });
    }


    /**
     *  @notice Fetches the existing Anvil config or deploys fresh mocks if none exist.
     *  @dev Broadcasts transactions locally using Forge Cheatcodes (`vm`) to spin up dummy 
     *       contracts.
     *  @return NetworkConfig The complete configuration struct containing local mock 
     *          addresses.
     */
    function getOrCreateAnvilEthConfig() public returns(NetworkConfig memory) {
        // Prevent redeploying mocks if they are already active in the state
        if(activeNetworkConfig.wethUsdPriceFeed != address(0)){
            return activeNetworkConfig;
        }

         // Begin recording transactions to deploy contracts on the local chain
        vm.startBroadcast();

         // Deploy mock Chainlink price feed for ETH/USD
        MockV3Aggregator ethUsdPriceFeed = new MockV3Aggregator(
            DECIMALS,
            ETH_USD_PRICE
        );
        
        // Deploy mock WETH ERC20 token for test transactions
        ERC20Mock wethMock = new ERC20Mock("WETH", "WETH", msg.sender, 1000e8);

        // Deploy mock Chainlink price feed for BTC/USD
        MockV3Aggregator btcUsdPriceFeed = new MockV3Aggregator(
            DECIMALS,
            BTC_USD_PRICE
        );

        // Deploy mock WBTC ERC20 token for test transactions
        ERC20Mock wbtcMock = new ERC20Mock("WBTC", "WBTC", msg.sender, 1000e8);

        // Terminate transaction broadcasting
        vm.stopBroadcast();

        // Return the newly created configuration struct with mock addesses (Construct and return the final local configurations)
        return NetworkConfig({
            wethUsdPriceFeed: address(ethUsdPriceFeed),
            wbtcUsdPriceFeed: address(btcUsdPriceFeed),
            weth: address(wethMock),
            wbtc: address(wbtcMock),
            deployerKey: DEFAULT_ANVIL_KEY
        });
    }

}